// <auto-generated />
using System;
using API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250909222059_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Models.BaseClasses.BaseAuditableEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeletedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PriceType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.HasKey("Id");

                    b.ToTable("BaseAuditableEntity");

                    b.HasDiscriminator<string>("PriceType").HasValue("BaseAuditableEntity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("API.Models.ProductTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("API.Models.Location", b =>
                {
                    b.HasBaseType("API.Models.BaseClasses.BaseAuditableEntity");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("Location");
                });

            modelBuilder.Entity("API.Models.MeasurementUnit", b =>
                {
                    b.HasBaseType("API.Models.BaseClasses.BaseAuditableEntity");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasIndex("Abbreviation")
                        .IsUnique()
                        .HasFilter("[Abbreviation] IS NOT NULL");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.HasDiscriminator().HasValue("MeasurementUnit");
                });

            modelBuilder.Entity("API.Models.PriceModels.Price", b =>
                {
                    b.HasBaseType("API.Models.BaseClasses.BaseAuditableEntity");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<bool>("IsPack")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PriceDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("UnitsPerPack")
                        .HasColumnType("bigint");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("ProductId");

                    b.HasIndex("ShopId");

                    b.HasDiscriminator().HasValue("Normal");
                });

            modelBuilder.Entity("API.Models.Product", b =>
                {
                    b.HasBaseType("API.Models.BaseClasses.BaseAuditableEntity");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<Guid>("UnitOfMeasureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasIndex("UnitOfMeasureId");

                    b.HasIndex("Name", "Variant")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL AND [Variant] IS NOT NULL");

                    b.ToTable("BaseAuditableEntity", t =>
                        {
                            t.Property("Name")
                                .HasColumnName("Product_Name");
                        });

                    b.HasDiscriminator().HasValue("Product");
                });

            modelBuilder.Entity("API.Models.Shop", b =>
                {
                    b.HasBaseType("API.Models.BaseClasses.BaseAuditableEntity");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("LocationId")
                        .IsUnique()
                        .HasFilter("[LocationId] IS NOT NULL");

                    b.ToTable("BaseAuditableEntity", t =>
                        {
                            t.Property("Name")
                                .HasColumnName("Shop_Name");
                        });

                    b.HasDiscriminator().HasValue("Shop");
                });

            modelBuilder.Entity("API.Models.StockList", b =>
                {
                    b.HasBaseType("API.Models.BaseClasses.BaseAuditableEntity");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("OwnerId");

                    b.ToTable("BaseAuditableEntity", t =>
                        {
                            t.Property("Name")
                                .HasColumnName("StockList_Name");
                        });

                    b.HasDiscriminator().HasValue("StockList");
                });

            modelBuilder.Entity("API.Models.StockListProduct", b =>
                {
                    b.HasBaseType("API.Models.BaseClasses.BaseAuditableEntity");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<Guid>("StockListId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("ProductId");

                    b.HasIndex("StockListId");

                    b.ToTable("BaseAuditableEntity", t =>
                        {
                            t.Property("ProductId")
                                .HasColumnName("StockListProduct_ProductId");

                            t.Property("Quantity")
                                .HasColumnName("StockListProduct_Quantity");
                        });

                    b.HasDiscriminator().HasValue("StockListProduct");
                });

            modelBuilder.Entity("API.Models.User", b =>
                {
                    b.HasBaseType("API.Models.BaseClasses.BaseAuditableEntity");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("User");
                });

            modelBuilder.Entity("API.Models.UserStockList", b =>
                {
                    b.HasBaseType("API.Models.BaseClasses.BaseAuditableEntity");

                    b.Property<Guid>("AddedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("StockListId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("StockListId");

                    b.HasIndex("UserId", "StockListId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL AND [StockListId] IS NOT NULL");

                    b.ToTable("BaseAuditableEntity", t =>
                        {
                            t.Property("IsActive")
                                .HasColumnName("UserStockList_IsActive");

                            t.Property("StockListId")
                                .HasColumnName("UserStockList_StockListId");
                        });

                    b.HasDiscriminator().HasValue("UserStockList");
                });

            modelBuilder.Entity("API.Models.PriceModels.PromotionPrice", b =>
                {
                    b.HasBaseType("API.Models.PriceModels.Price");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsBulk")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPromotion")
                        .HasColumnType("bit");

                    b.Property<long?>("PerBulk")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("Promotion");
                });

            modelBuilder.Entity("API.Models.ProductTag", b =>
                {
                    b.HasOne("API.Models.Product", null)
                        .WithMany("Tags")
                        .HasForeignKey("ProductId");
                });

            modelBuilder.Entity("API.Models.PriceModels.Price", b =>
                {
                    b.HasOne("API.Models.Product", "Product")
                        .WithMany("Prices")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("API.Models.Shop", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("API.Models.Product", b =>
                {
                    b.HasOne("API.Models.MeasurementUnit", "UnitOfMeasure")
                        .WithMany()
                        .HasForeignKey("UnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UnitOfMeasure");
                });

            modelBuilder.Entity("API.Models.Shop", b =>
                {
                    b.HasOne("API.Models.Location", "Location")
                        .WithOne()
                        .HasForeignKey("API.Models.Shop", "LocationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("API.Models.StockList", b =>
                {
                    b.HasOne("API.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("API.Models.StockListProduct", b =>
                {
                    b.HasOne("API.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("API.Models.StockList", "StockList")
                        .WithMany("StockListProducts")
                        .HasForeignKey("StockListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("StockList");
                });

            modelBuilder.Entity("API.Models.UserStockList", b =>
                {
                    b.HasOne("API.Models.StockList", "StockList")
                        .WithMany("SharedUsers")
                        .HasForeignKey("StockListId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("API.Models.User", "User")
                        .WithMany("StockLists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("StockList");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Models.Product", b =>
                {
                    b.Navigation("Prices");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("API.Models.StockList", b =>
                {
                    b.Navigation("SharedUsers");

                    b.Navigation("StockListProducts");
                });

            modelBuilder.Entity("API.Models.User", b =>
                {
                    b.Navigation("StockLists");
                });
#pragma warning restore 612, 618
        }
    }
}
